### ISSUE TITLE
NLNZ Metadata Extractor failing

### ISSUE THREAD

**Issue by dchandekstark** [harvard-lts/FITSservlet#2]
```
java.lang.NullPointerException
	at nz.govt.natlib.meta.config.Config.readConfig(Config.java:563)
	at nz.govt.natlib.meta.config.Config.<init>(Config.java:198)
	at nz.govt.natlib.meta.config.Config.getInstance(Config.java:263)
	at edu.harvard.hul.ois.fits.tools.nlnz.MetadataExtractor.extractInfo(MetadataExtractor.java:71)
	at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:275)
	at java.lang.Thread.run(Thread.java:662)
Exception in thread "NLNZ Metadata Extractor" java.lang.NullPointerException
	at nz.govt.natlib.meta.config.Config.setXMLBaseURL(Config.java:375)
	at edu.harvard.hul.ois.fits.tools.nlnz.MetadataExtractor.extractInfo(MetadataExtractor.java:71)
	at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:275)
	at java.lang.Thread.run(Thread.java:662)
```

**Comment by dchandekstark** [comment]
I'm guessing you need to add some the of the jars under lib/nzmetool in the FITS dist to the shared dir?

**Comment by dchandekstark** [comment]
Or maybe xml/nlnz has to be added to CLASSPATH?

**Comment by DaveSiegel** [comment]
I'm not able to reproduce this. Are all the .jars in the correct place?

**Comment by dchandekstark** [comment]
This is my shared/lib directory:

```sh
lrwxrwxrwx 1 tomcat tomcat     29 Aug  5 22:12 annotations-api.jar -> ../../lib/annotations-api.jar
-rw-r--r-- 1 tomcat tomcat 445288 May 18 14:50 antlr-2.7.7.jar
-rw-r--r-- 1 tomcat tomcat 895124 May 18 14:50 antlr-3.2.jar
-rw-r--r-- 1 tomcat tomcat 151989 May 18 14:50 antlr-runtime-3.2.jar
-rw-r--r-- 1 tomcat tomcat 140264 May 18 14:50 byteseek-1.1.1.jar
-rw-r--r-- 1 tomcat tomcat 232019 May 18 14:50 commons-beanutils-1.8.3.jar
-rw-r--r-- 1 tomcat tomcat 206711 May 18 14:50 commons-beanutils-core-1.8.3.jar
-rw-r--r-- 1 tomcat tomcat  41123 May 18 14:50 commons-cli-1.2.jar
-rw-r--r-- 1 tomcat tomcat  58160 May 18 14:50 commons-codec-1.4.jar
-rw-r--r-- 1 tomcat tomcat 575389 May 18 14:50 commons-collections-3.2.1.jar
-rw-r--r-- 1 tomcat tomcat 241367 May 18 14:50 commons-compress-1.4.1.jar
-rw-r--r-- 1 tomcat tomcat 354491 May 18 14:50 commons-configuration-1.8.jar
-rw-r--r-- 1 tomcat tomcat 160519 May 18 14:50 commons-dbcp-1.4.jar
-rw-r--r-- 1 tomcat tomcat 196768 May 18 14:50 commons-digester-2.1.jar
-rw-r--r-- 1 tomcat tomcat 305001 May 18 14:50 commons-httpclient-3.1.jar
-rw-r--r-- 1 tomcat tomcat 185140 May 18 14:50 commons-io-2.4.jar
-rw-r--r-- 1 tomcat tomcat 284220 May 18 14:50 commons-lang-2.6.jar
-rw-r--r-- 1 tomcat tomcat  60841 May 18 14:50 commons-logging-1.1.1.jar
-rw-r--r-- 1 tomcat tomcat  96221 May 18 14:50 commons-pool-1.5.4.jar
-rw-r--r-- 1 tomcat tomcat 143058 May 18 14:50 droid-command-line-6.1.3.jar
-rw-r--r-- 1 tomcat tomcat  41785 May 18 14:50 droid-container-6.1.3.jar
-rw-r--r-- 1 tomcat tomcat  79503 May 18 14:50 droid-core-6.1.3.jar
-rw-r--r-- 1 tomcat tomcat 139913 May 18 14:50 droid-core-interfaces-6.1.3.jar
-rw-r--r-- 1 tomcat tomcat  15500 May 18 14:50 droid-export-6.1.3.jar
-rw-r--r-- 1 tomcat tomcat   7687 May 18 14:50 droid-export-interfaces-6.1.3.jar
-rw-r--r-- 1 tomcat tomcat 688774 May 18 14:50 droid-help-6.1.3.jar
-rw-r--r-- 1 tomcat tomcat  79443 May 18 14:50 droid-report-6.1.3.jar
-rw-r--r-- 1 tomcat tomcat  15847 May 18 14:50 droid-report-interfaces-6.1.3.jar
-rw-r--r-- 1 tomcat tomcat 308306 May 18 14:50 droid-results-6.1.3.jar
```

Am I missing something?

**Comment by dchandekstark** [comment]
I see that I followed the instructions in README.TXT, which includes copying certain jars into $CATALINA_HOME/shared/lib.  README.md doesn't mention this.  Should I remove the shared jars?

**Comment by dchandekstark** [comment]
No, the jars need to be there ...

**Comment by DaveSiegel** [comment]
I've made an error with the NLNZ process and am tracking it down. Might take a while.

The jars need to be there except annotations-api.jar which just needs to be in tomcat's /lib. I see you made a symlink which is fine.

**Comment by DaveSiegel** [comment]
Well, I am not having much luck. I've tried all sorts of configurations and have changed the fits code but all lead to dead ends. Here's my last stack trace:

Exception in thread "NLNZ Metadata Extractor" java.lang.NullPointerException
	at nz.govt.natlib.meta.config.Config.setXMLBaseURL(Config.java:375)

I am going to try and have a look at their source code to see what work around I can create.

**Comment by DaveSiegel** [comment]
After consulting the original FITS architect I am going to mark this release as not supporting NLNZ. Perhaps if LTS upgrades the NLNZ code base this will change. In the mean time please comment-out the nlnz tool in ./xml/fits.xml. Tika will process most of the same file types that nlnz does at this time.

**Comment by dchandekstark** [comment]
Fair enough, thanks!
