### ISSUE TITLE
droid class not found exception

### ISSUE THREAD

**Issue by pautri** [harvard-lts/FITSservlet#29]
Hi,

We're getting the error below when running FITS 1.4.0 or 1.4.1 with FITSservlet 1.2.0 on Tomcat 7.0.64 with Java 1.8.0_60. It was working fine with FITS 1.3.0 so it seems to have something to do with the Droid update. The error does not occur though when running FITS stand-alone from the command line.

Any idea what the problem might be?

Thanks,

Paul

```2019-04-24 16:09:47 - ERROR - FitsServlet:382 - Unexpected exception: Unexpected Throwable:
javax.servlet.ServletException: Unexpected Throwable:
	at edu.harvard.hul.ois.fits.service.pool.FitsWrapper.<init>(FitsWrapper.java:51)
	at edu.harvard.hul.ois.fits.service.pool.FitsWrapperFactory.create(FitsWrapperFactory.java:25)
	at edu.harvard.hul.ois.fits.service.pool.FitsWrapperFactory.create(FitsWrapperFactory.java:18)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at edu.harvard.hul.ois.fits.service.servlets.FitsServlet.sendFitsExamineResponse(FitsServlet.java:364)
	at edu.harvard.hul.ois.fits.service.servlets.FitsServlet.doPost(FitsServlet.java:298)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: uk/gov/nationalarchives/droid/core/SignatureParseException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:98)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:56)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:243)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:123)
	at edu.harvard.hul.ois.fits.service.pool.FitsWrapper.<init>(FitsWrapper.java:45)
	... 30 more
Caused by: java.lang.ClassNotFoundException: uk.gov.nationalarchives.droid.core.SignatureParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more```

**Comment by daveneiman** [comment]
Hello,

An initial guess would be to make sure you have properly updated your catalina.properties file in the Tomcat instance you are using. Directions for doing this are [here](https://github.com/harvard-lts/FITSservlet#catalinaproperties-example).

Also, make sure the context.xml file in the META-INF directory is configured properly as shown in GitHub [here](https://github.com/harvard-lts/FITSservlet/blob/dev/src/main/webapp/META-INF/context.xml).

Would be interested to hear how it goes.
Thanks!

**Comment by pautri** [comment]
Hi, thanks for the quick reply. Both are configured as indicated (they already were before upgrading to FITS 1.4.0/1.4.1).

**Comment by daveneiman** [comment]
Are you still experiencing the same problem or has this been resolved. If not resolved, please indicate, as we will attempt to recreate locally. Any additional information you could supply might be helpful.
Thanks.

**Comment by pautri** [comment]
We're still experiencing the same problem (the configuration remained unchanged, as it was already correct). We're running SUSE Linux Enterprise Server 12 with the Tomcat/Java versions mentioned above. Thanks for looking into this.

**Comment by daveneiman** [comment]
We were not able to replicate this using FITS Servlet 1.2.0, Tomcat 8.5 (we no longer can use 7.x), FITS 1.4.0, and Java 8.0_181 on OSX. We realized the application would not have even gotten as far as the DROID error you see unless the entries in catalina.properties were set up properly. Any Java classes within any tools embedded within FITS are loaded by a custom class loader in FITS. These are JAR files within sub-directories in the FITS deployment `lib` directory, including `lib/droid`. There should be many JAR files within this sub-directory including about 10 that are named `droid-*.jar`.

When deployed verify the version of FITS being accessed by the web application with the endpoint `<tomcat-fits-url>/version` which should return the version of FITS being accessed by the FITS servlet. Not quite sure where to go from here since we cannot reproduce the issue.

**Comment by pautri** [comment]
the version info page also gave the same error.

I tried running it in a freshly installed Tomcat 8.5 and it worked fine. I think I narrowed it down to something to do with the log4j setup. Something seems to be different there in the newer FITS versions, at least these include a log4j jar in lib/droid, whereas 1.3.0 did not. In Tomcat 7 (or in our particular Tomcat 7 setup) for some reason it fails to load the log4j.properties file from the webapp if it's not explicitly configured, see below. The file is there and is readable for the tomcat user, so I figured it might have something to do with the jndi wrapper. If I explicitly set the log4j.configuration in catalina.properties to the log4j.properties file path in the webapp, it works fine.

We're still running one or two ancient applications that do not run on Tomcat 8 or higher, but on our production setup we're running FITS in it's own Tomcat, so I could either update that to 8.5, or use the explicit log4j configuration option.

```
log4j:ERROR Could not read configuration file from URL [jndi:/localhost/fits/WEB-INF/classes/log4j.properties].
java.lang.IllegalStateException: Illegal class loader binding
        at org.apache.naming.resources.DirContextURLStreamHandler.get(DirContextURLStreamHandler.java:228)
        at org.apache.naming.resources.DirContextURLStreamHandler.openConnection(DirContextURLStreamHandler.java:90)
        at java.net.URL.openConnection(URL.java:972)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:555)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.apache.log4j.Logger.getLogger(Logger.java:117)
        at edu.harvard.hul.ois.fits.tools.droid.Droid.<clinit>(Droid.java:49)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:100)
        at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:58)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:243)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:123)
        at edu.harvard.hul.ois.fits.service.pool.FitsWrapper.<init>(FitsWrapper.java:45)
        at edu.harvard.hul.ois.fits.service.pool.FitsWrapperFactory.create(FitsWrapperFactory.java:25)
        at edu.harvard.hul.ois.fits.service.pool.FitsWrapperFactory.create(FitsWrapperFactory.java:18)
        at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
        at edu.harvard.hul.ois.fits.service.servlets.FitsServlet.sendFitsVersionResponse(FitsServlet.java:402)
        at edu.harvard.hul.ois.fits.service.servlets.FitsServlet.doGet(FitsServlet.java:190)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
log4j:ERROR Ignoring configuration file [jndi:/localhost/fits/WEB-INF/classes/log4j.properties].
```
